### ISSUE TITLE
Responsible_id should be required

### ISSUE THREAD

**Issue by eilst** [savoirfairelinux/project-addons#188]
**Is your feature request related to a problem? Please describe.**

A task and activity must have an responsible. 'responsible_id' should be required. However, if this is done, the module doesn't build, The most likely reason is that there are 'project.task' records being inserted without responsible.

**Describe the solution you'd like**
'responsible_id' field should be required and this shouldn't cause any error.
 
**Additional context**
Error when responsible_id  is required
2018-11-13 23:13:32,113 682 ERROR 11.0_nov_1310 odoo.sql_db: bad query: b'ALTER TABLE "project_task" ALTER COLUMN "responsible_id" SET NOT NULL'
ERROR: column "responsible_id" contains null values

2018-11-13 23:13:32,113 682 WARNING 11.0_nov_1310 odoo.schema: Table 'project_task': unable to set NOT NULL on column 'responsible_id'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "project_task" ALTER COLUMN "responsible_id" SET NOT NULL
Traceback (most recent call last):
  File "/opt/odoodev/git/odoo/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "/opt/odoodev/git/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoodev/git/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: column "responsible_id" contains null values

**Comment by wbeverly** [comment]
@eilst Is this still applicable? responsible_ID seems required in all EV AC and TA

**Comment by eilst** [comment]
This was fixed changing the field to requested on the front end, without constraints on  the db
