### ISSUE TITLE
Event duplication Error

### ISSUE THREAD

**Issue by eilst** [savoirfairelinux/project-addons#299]
**Describe the bug**
When an event (project_project) is duplicated, an error occurs.
**To Reproduce**
Click on duplicate at the top of the event form page

**Expected behavior**
The event should be duplicated 
**Error Message**
Traceback (most recent call last):
  File "/opt/odoodev/git/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoodev/git/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoodev/git/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoodev/git/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoodev/git/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoodev/git/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoodev/git/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoodev/git/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoodev/git/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoodev/git/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoodev/git/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoodev/git/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoodev/git/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoodev/git/odoo/addons/project/models/project.py", line 245, in copy
    project = super(Project, self).copy(default)
  File "/opt/odoodev/git/odoo/odoo/models.py", line 3946, in copy
    new = self.with_context(lang=None).create(vals)
  File "/opt/odoodev/git/server-tools/auditlog/models/rule.py", line 206, in create_full
    new_record = create_full.origin(self, vals, **kwargs)
  File "/opt/odoodev/git/project-addons/project_event/models/project_project.py", line 135, in create
    return super(Project, self).create(vals)
  File "/opt/odoodev/git/odoo/addons/project/models/project.py", line 256, in create
    project = super(Project, self).create(vals)
  File "/opt/odoodev/git/odoo/addons/mail/models/mail_alias.py", line 223, in create
    )).create(vals)
  File "/opt/odoodev/git/odoo/addons/mail/models/mail_thread.py", line 248, in create
    thread.message_auto_subscribe(list(create_values), values=create_values)
  File "/opt/odoodev/git/odoo/addons/mail/models/mail_thread.py", line 2173, in message_auto_subscribe
    self.message_subscribe(partner_ids=[pid], subtype_ids=subtypes, force=(subtypes != None))
  File "/opt/odoodev/git/odoo/addons/project/models/project.py", line 311, in message_subscribe
    partner_ids=[partner_id], channel_ids=None, subtype_ids=None, force=False)
  File "/opt/odoodev/git/odoo/addons/mail/models/mail_thread.py", line 2024, in message_subscribe
    self.sudo().write({'message_follower_ids': gen})
  File "/opt/odoodev/git/server-tools/auditlog/models/rule.py", line 273, in write_full
    result = write_full.origin(self, vals, **kwargs)
  File "/opt/odoodev/git/project-addons/project_event/models/project_task.py", line 381, in write
    self.update_reservation_event(vals)
  File "/opt/odoodev/git/project-addons/project_event/models/project_task.py", line 426, in update_reservation_event
    self.ensure_one()
  File "/opt/odoodev/git/odoo/odoo/models.py", line 4366, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: project.task()

**Comment by wbeverly** [comment]
Has this been fixed? Now there is no traceback but this alert :

https://www.awesomescreenshot.com/image/3913983/81bb2ee21d84152dec5291b5e615a05d

**Comment by jananjoy** [comment]
@eilst : When an event is linked with only one activity. The functionality works.  But an event is linked to more than one activity. Then   Event duplication Error #299  exists in the event form.  
Note: This functionality needs to be verified with the functional team. If the functionality is valid, Please extend the requirements for activity and task form too.

**Comment by wbeverly** [comment]
JJ will have a look throught this task because the duplication possibility is needed. 
We should be able to duplicate an event that has more than 1 activity.
It should copy all AC assigned to that EV and all TA assigned to each AC.

**Comment by jananjoy** [comment]
Already task is created for this task. Known issue.
